{
  "formatVersion": "1.1",
  "component": {
    "group": "com.therouter",
    "module": "therouter_plugin",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "therouter_plugin-1.2.1.jar",
          "url": "therouter_plugin-1.2.1.jar",
          "size": 99416,
          "sha512": "d426a2c20533cf626d928deadf03b6e10f6476d768e9745b6da9f012bd0645c980ba6a9ad665e60b05ea19eb262729b93197efba1bcbc536583f488e27411891",
          "sha256": "7563e17bcb3d46c188f52c4b7d040b3559fd9af28f4b8efc5d3a1f6fe6ea081c",
          "sha1": "c753459a437e4e94eb816dbc762332a9ba88bd0e",
          "md5": "c5cb038122af1eeec46ab1340bae3ed7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        }
      ],
      "files": [
        {
          "name": "therouter_plugin-1.2.1.jar",
          "url": "therouter_plugin-1.2.1.jar",
          "size": 99416,
          "sha512": "d426a2c20533cf626d928deadf03b6e10f6476d768e9745b6da9f012bd0645c980ba6a9ad665e60b05ea19eb262729b93197efba1bcbc536583f488e27411891",
          "sha256": "7563e17bcb3d46c188f52c4b7d040b3559fd9af28f4b8efc5d3a1f6fe6ea081c",
          "sha1": "c753459a437e4e94eb816dbc762332a9ba88bd0e",
          "md5": "c5cb038122af1eeec46ab1340bae3ed7"
        }
      ]
    }
  ]
}
